<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Library.fs" />
    <Compile Include="Commons/Commons.fs" />
    <Compile Include="Slices/User/User.fs" />
    <Compile Include="Slices/User/IUserService.fs" />
    <Compile Include="Infrastructure/Services/IMailSender.fs" />

  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.SystemTextJson" Version="1.4.36" />
    <PackageReference Include="FsToolkit.ErrorHandling" Version="5.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
    <PackageReference Include="Sharpino.Core" Version="5.0.4" />
  </ItemGroup>

</Project>
