<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TitForTat.Shared</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Library.fs" />
    <Compile Include="Commons/Commons.fs" />
    <Compile Include="Commons/ConverterUtils.fs"/>
    <Compile Include="Slices/User/User.fs" />
    <Compile Include="Slices/User/Events.fs" />
    <Compile Include="Slices/User/Commands.fs" />
    <Compile Include="Slices/User/IUserService.fs" />
    <Compile Include="Slices/Coop/Coop.fs" />
    <Compile Include="Slices/Coop/Events.fs" />
    <Compile Include="Slices/Coop/Commands.fs" />
    <Compile Include="Slices/Coop/ICoopService.fs" />
    <Compile Include="Slices/Ledger/Ledger.fs" />
    <Compile Include="Slices/Ledger/Events.fs" />
    <Compile Include="Slices/Ledger/Commands.fs" />
    <Compile Include="Slices/Ledger/ILedgerService.fs" />
    <Compile Include="Infrastructure/Services/IMailSender.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.SystemTextJson" Version="1.4.36" />
    <PackageReference Include="FsToolkit.ErrorHandling" Version="5.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
    <PackageReference Include="Sharpino.Core" Version="5.0.4" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources/SharedResources.resx">
      <LogicalName>TitForTat.Shared.SharedResources.resources</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources/SharedResources.it.resx">
      <LogicalName>TitForTat.Shared.SharedResources.it.resources</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
